services:
  backend:
    container_name: backend
    build:
      context: ./apps/back
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: mongodb_container
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb

  redis:
    image: "${REDIS_IMAGE}"
    container_name: redis_container
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
      - ${REDIS_CONF_PATH}:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/certs:ro
      - ./nginx/start.sh:/start.sh
    entrypoint: ["/bin/sh", "/start.sh"]
    depends_on:
      - backend
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./apps/front
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
  redis-data:
    driver: local
