version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./apps/back
    env_file:
      - .env
    depends_on:   
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/certs:ro
      - ./nginx/start.sh:/start.sh
    entrypoint: ["/bin/sh", "/start.sh"]
    depends_on:
      - backend
    restart: always

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
