version: '3.8'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./ssl:/etc/letsencrypt/live
      - ./ssl:/certs
    entrypoint: [ "sh", "-c", "certbot certonly --standalone --non-interactive --agree-tos --email seregapax@gmail.com -d milki.space && cp /etc/letsencrypt/live/milki.space/fullchain.pem /certs/server.crt && cp /etc/letsencrypt/live/milki.space/privkey.pem /certs/server.key" ]

  localtunnel-server:
    image: boro/localtunnel-server:latest
    container_name: localtunnel-server
    environment:
      port: 3000
    restart: always
    network_mode: host

  nginx:
    image: nginx:alpine
    container_name: localtunnel-nginx
    depends_on:
      - certbot
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./ssl:/certs:ro
    entrypoint: >
      sh -c "while [ ! -f /certs/server.crt ]; do
                echo 'Waiting for certificate...';
                sleep 2;
              done;
              echo 'Certificate found, starting nginx';
              exec nginx -g 'daemon off;'"