version: '3.8'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./ssl:/etc/letsencrypt/live
      - ./ssl:/certs
    command: >
      sh -c "certbot certonly --standalone --non-interactive --agree-tos --email ${EMAIL} --domains ${DOMAIN} &&
      cp /etc/letsencrypt/live/${DOMAIN}/fullchain.pem /certs/server.crt &&
      cp /etc/letsencrypt/live/${DOMAIN}/privkey.pem /certs/server.key"

  localtunnel-server:
    image: boro/localtunnel-server:latest
    container_name: localtunnel-server
    restart: always
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: localtunnel-nginx
    restart: always
    depends_on:
      - certbot
      - localtunnel-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./ssl:/certs:ro
